### ISSUE TITLE
Adding ability for a callback for onClose

### ISSUE THREAD

**Issue by nasiefk** [postmelee/react-native-animated-bottom-sheet#1]
Hi,

I am trying to perform some code when the state of the sheet is invisible. I am trying to pass a callback like onClose.

My suggestion is to 
1.   add `onClose: () => any;` in IProp interface
2. Whenever `isVisible` is set to `false`, add a callback that invokes `onClose`

When do you expect this to be done?

Thanks in Advance

**Comment by postmelee** [comment]
Sorry for late response. That sounds great! I'll add "onClose" props and that will be evaluated every close event (press backdrop, swipe down) as soon as possible! Thank you for make an issue.

**Comment by postmelee** [comment]
Hi @nasiefk, [v.1](https://github.com/postmelee/react-native-animated-bottom-sheet/releases/tag/v.1) has released with your suggestion! please check and let me know else! Thank you.
